--GERAR NOVA VIAGEM QUANDO A ANTIGA ESTIVAR CANCELADA PELA PANCARD
--AO FAZER PELO GS ELE NÃO HABILITA O BOTÃO DE GERAR LOGO APOS SIMULAR
--EXISTEM DUAS OPÇÕES PARA RESOLVER O PROBLEMA 
--1º FORÇAR O VB6 A LIBERAR O CAMPO PARA SETANDO TUDO ONDE O CAMPO.VISIBLED = TRUE
--2º ABRIR A BUSINESS NA PAGINA DE TESTES DO MARCOS COLOCAR O SEQUENCIAL E NUMERO DA ORDEM E CLICAR NO BOTÃO "INCLUIR VIAGEM PANCARD"

--SQL USADA NA BUSINESS CASO JA EXISTA UM CADASTRO COM O SEQUENCIAL ELE VAI TENTAR NOVAMENTE PELO NUMERO DA ORDEM
SELECT TOP (1) CASE COUNT(CF.id) WHEN 0 THEN CTRC.Sequencial
WHEN 1 THEN CTRC.CodOrdemEmbarque
WHEN 2 THEN CTRC.NumConhecto 
ELSE CONVERT(decimal(14,0),(CONVERT(VARCHAR(8),GETDATE(),112)+REPLACE(CONVERT(VARCHAR,GETDATE(),108),':',''))) END AS 'IdCliente'
FROM CartaFrete CF INNER JOIN ConhecimentosTransporte CTRC ON CTRC.Sequencial = CF.Sequencial 
LEFT OUTER JOIN CartaFrete_Ocorrencia O ON O.IdCartaFrete = CF.Id 
WHERE O.DescricaoOcorrencia = 'INSERIR VIAGEM' AND O.Erro like '0 - OPERAÇÃO REALIZADA COM SUCESSO' AND  cf.Sequencial = 80000085675 AND CF.NumOrdemEmbarque = 8087806 
GROUP BY CTRC.Sequencial, CTRC.CodOrdemEmbarque, CTRC.NumConhecto