algoritmo "Aula 12 - Rotinas - FazSomaProcedimento"
// Função : Exercicio
// Autor : Emanuel Neto
// Data : 21/07/2022
// Seção de Declarações 
var
 X, Y: inteiro

Procedimento Soma (A, B: inteiro)
inicio
   LimpaTela
   Escreval  ("Recebi o valor ", A)
   Escreval  ("Recebi o valor ", B)
   Escreval  ("A soma entre os dois e ", A + B)
FimProcedimento
inicio
      X <- 5
      Y <- 3
      Soma (X, Y)
fimalgoritmo
