algoritmo "Emprestimo Creuza"
// Função : Exercicios
// Aluno : Emanuel Neto
// Data : 18/07/2022
// Seção de Declaraçõe
var
    emprestimo, parcela, valorparcela: real
inicio
Escreval ("Qual o valor o valor que gostaria solicitar? ", emprestimo)
leia (emprestimo)
Escreval ("Em quantas parcelas deseja solicitar? ", parcela)
leia  (parcela)
valorparcela <- emprestimo + (emprestimo * 20 / 100)
Escreval ("O valor da parcela é dê: R$ ", valorparcela/10)
fimalgoritmo
