algoritmo "Viajem para os EUA da Creuza"
// Função : Exercicios
// Aluno : Emanuel Neto
// Data : 18/07/2022
// Seção de Declaraçõe
var
    dolar, reais, conversao: real
inicio
Escreval ("Qual a cotação atual do Dolar? ", dolar)
leia (dolar)
Escreval ("Quantos reais você tem? ", reais)
leia (reais)
conversao <- (reais/dolar)
Escreval ("É possivel comprar", conversao, "dolares com o seu dinheiro")


fimalgoritmo
