algoritmo "Estrutura de repetição - Conteatequando"
// Função : Exercicios
// Autor : Emanuel Neto
// Data : 19/07/2022
// Seção de Declarações
var
contador, salto ,valor:  inteiro
inicio
contador <-   0
Escreva ("Quer contar ate quando? ")
leia(valor)
Escreva ("Qual sera o valor do salto? ")
leia(salto)
Enquanto (contador <= valor) faca
   EscrevaL (contador)
   contador <- contador + salto
FimEnquanto
Escreval ("Terminei de contar")
fimalgoritmo
