--select * from ConhecimentosTransporte where NumConhecto = 36218 and CodUF = 'MT'
--Sequencial	CodPais	CodUF	NumConhecto	SerieConhecto	CodFilialEmitente	DataEmissao	HoraEmissao	NumFormulario	CodVeiculo	CodFornecedor	CodMotorista	NumRelatorioEmbarque	CodPedidoFrete	CodOrdemEmbarque	CodCondicaoFrete	CodigoCFOP	CodClienteEmitente	CodClienteDestinatario	CodClientePagto	CodRota	CodUsuarioAprovCortesia	IndConsigRedesp	CodConsigRedesp	NumConhectoConsigRedesp	ValorNF	QuantVolumes	CodEspecieMercadoria	Marca	CodNaturezaCarga	CodUnidadeMedida	Numero	FretePesoVolume	FreteValor	TarifaFreteEmpresa	TarifaFreteMotorista	DiferencaFreteAgregado	IndPagtoDiferenca	QuantidadeSaida	QuantidadeChegada	QuantChegFaturamento	UnidadeFrete	TotalFreteMotorista	ValorAdiantamento	SEC_CAT	Pedagio	IndFaturaPedagio	ValorReajusteFrete	Despacho	Outros	ValorIRRFMotorista	TarifaSEFAZ	BaseCalculoICMS	AliquotaICMSFrete	ValorICMSFrete	IndFaturaICMSFrete	ValorICMSMercadoria	DespesaAdubo	IndPagtoDespesaAdubo	Desconto	CodUsuarioAprovDesconto	NumeroClassificacao	ValorClassificacao	IndFaturaClassificacao	ValorTotalFrete	ValorLiquidoFrete	CodMoeda	SituacaoConhecto	ObsConhecto	Gerado	CodObservacaoICMS	IndicadorICMS_NF	IndicadorComplemento	IndFaturaComplemento	IndComissaoComplemento	ValorRetidoINSS	ValorRetidoSestSenat	Saldo	Agregado	Adto	ValorICMSRetido	ResponsavelFreteAgregado	CodUsuarioCriacao	CodFilialCriacao	DataCriacao	CodUsuarioAlteracao	CodFilialAlteracao	DataAlteracao	DataDigitacaoFreteAgregado	BaseCalcICMSRetido	AliquotaICMSRetido	IndEnvioXML	IndEnvioSPED	ResponsavelSeguro	CodCorretora	NumApoliceSeguro	NumAverbacaoSeguro	ValorMercSeguro	ResponsavelValePedagio	TipoDispositivoValePedagio	EmpresaValePedagio	DataContratoValePedagio	NumCartaoValePedagio	CodClienteColeta	CodClienteEntrega	Lotacao	ModeloDocumento	TipoServico	IndProdutoPerigoso	CST	LiberaReemissaoCF	IndReemissaoCF	CodReemitenteCF	CodSeguradora	TipoConhecimento	IndMigracaoFrota	CIOT	ValorEmbarqueOutros	ValorCombustivel	NumReqCombustivel	CodFornecCombustivel	ComplementoObsICMS	BaseCalculoNFe	IndTipoTributacao	IndTipoSubstituicao	TarifaSaque	TarifaTransferencia	CodUsuarioAutPagto	DataAutPagto	IndPagtoPedagioSub	TipoPagtoPedagioSub	DataCTeAnulacao	CodControleCaramuru	CodOrdemMDFE	ChaveCTeMultimodal	DescontoTaxaAdm	IndCompEstadia	CodFilialComissao	CodRegiao	SeguroAverbado
--10000022238	1	MT	36218	0	CON	2023-05-18 00:00:00	2023-05-18 08:46:10.000	0	87755	92000165	92000268	51002054	1007606	51008110	1	6.353	1023983	55000009	1023983	18583	NULL	NULL	NULL	NULL	114369.67	NULL	1	NULL	1	KG	NULL	NULL	NULL	2800.0000	0.00	NULL	NULL	1000.000	1000.000	NULL	1	0.00	NULL	NULL	NULL	NULL	NULL	NULL	114.36	NULL	2800.0000	0.00	0.00	0.00	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	2800.00	2995.16	1	Emitido		S	965	NULL	NULL	NULL	NULL	NULL	NULL	S	S	S	NULL	NULL	12622	CG	2023-05-18 08:46:10.000	12622	CG	2023-05-18 09:54:44.000	NULL	NULL	NULL	NULL	NULL	4	NULL	NULL	NULL	NULL	0	NULL	NULL	NULL	NULL	1024301	1014209	S	CT-e	0	NULL	40	NULL	NULL	NULL	1082958	Complemento	NULL	NULL	NULL	NULL	NULL	NULL	Complemento de Estadia Ref Ao Cte 35819 Autorizado Danilo Rodrigues 	NULL	NULL	NULL	NULL	NULL	NULL	NULL	N	NULL	NULL	NULL	NULL	NULL	4.90	S	AGB	28	0.00


select * from ConhecimentosComplementados where 10000022238 in (SeqConhecimentoComplementar,SeqConhecimentoComplementado)
--delete from ConhecimentosComplementados where 10000022238 in (SeqConhecimentoComplementar,SeqConhecimentoComplementado)


select * from RODOMAIOR_GSe.dbo.mdfe where Sequencial = 470992
--update RODOMAIOR_GSe.dbo.MDFe set Status = 0 where Sequencial = 470992
exec MonitoraMDFe 33013439
exec MonitoraMDFe 33013435
